/** Copy for the blog post page (/blogs/details). */
export const blogPost = {
  section1HeroSection: "SECTION 1: HERO SECTION & OVERLAPPING FEATURED IMAGE (Height: 684px)",
  blogDetails: "Blog Details",
  insideTheLogicIc: "Inside the Logic IC Trainer Kit's 16 profiles",
  whyWeChoseA: "Why we chose a profile-based architecture over hardcoded logic families to improve flexibility, scalability, maintainability, and long-term adaptability across diverse applications.",
  innosinoTeam: "Innosino Team",
  n8MinRead: "8 min read",
  embeddedSystems: "Embedded Systems",
  section2ArticleBody: "SECTION 2: ARTICLE BODY WITH 3-COLUMN LAYOUT",
  tableOfContent: "Table of Content",
  shareThisPost: "Share this post",
  whenEngineeringTheLogic: "When engineering the Logic IC Trainer Kit, our main engineering goal was clear: creating a seamless, error-resilient learning platform where students and embedded engineers could experiment with digital logic without the constant friction of fragile wiring, confusing pinouts, or burnt integrated circuits.",
  theHardcodingProblem: "The Hardcoding Problem",
  hardwareShouldAdaptTo: "“Hardware should adapt to the learner. The learner should not have to adapt to the kit.”",
  theProfileSchema: "The Profile Schema",
  the16Profiles: "The 16 Profiles",
  wePreLoaded16: "We pre-loaded 16 core profile presets covering standard combinational and sequential ICs—from NAND/NOR clusters to dual D-type flip-flops and 4-bit binary counters. Learners can toggle between these modes via an intuitive rotary encoder with OLED visual feedback.",
  realTimeVisualization: "Real-Time Visualization",
  everyGateInputAnd: "Every gate input and output transition is buffered and rendered on a two-tier LED status ring around the socket. When an invalid logic combination or bus contention is detected, the board immediately flags the error zone in amber without cutting system power, facilitating active troubleshooting.",
  whatItTaughtUs: "What It Taught Us",
  movingFromFixedFunction: "Moving from fixed-function hardware to a profile-centric architecture shortened testing setup cycles by over 70% and eliminated 95% of accidental chip burnouts during lab sessions. This modular principle has now become a standard cornerstone across all Innosino educational and testing devices.",
  logicIcTrainerKit: "Logic IC Trainer Kit",
  weTurnAmbitiousConcepts: "We turn ambitious concepts from single proof of concept through to production readiness.",
};
