/** Copy for the Privacy Policy page (/privacy-policy). */
export const privacyPolicy = {
  section1HeroSection: "SECTION 1: HERO SECTION (Height: 520px)",
  privacyPolicy: "Privacy Policy",
  privacyPolicy2: "PRIVACY POLICY",
  lastUpdatedJuly1: "LAST UPDATED · JULY 1, 2026",
  privacyPolicy3: "Privacy Policy",
  innosinoBuildsHardwareAnd: "INNOSINO builds hardware and embedded systems. This policy explains what information we collect through our website and how we use it. By using this site, you agree to what’s described below.",
  informationWeCollect: "Information We Collect",
  howWeUseIt: "How We Use It",
  respondToProjectInquiries: "Respond to project inquiries and provide support.",
  improveTheWebsiteAnd: "Improve the website and understand how it’s used.",
  sendUpdatesOnlyIf: "Send updates only if you’ve opted in—never sold to third parties.",
  dataSharing: "Data Sharing",
  weDonTSell: "We don’t sell your data. We may share it with service providers who help us run the site (e.g. hosting, analytics), bound by confidentiality, or when required by law.",
  dataRetentionSecurity: "Data Retention & Security",
  weKeepPersonalData: "We keep personal data only as long as needed for the purposes above, and use reasonable technical safeguards to protect it. No method of transmission is 100% secure, so we can’t guarantee absolute security.",
  yourRights: "Your Rights",
  youCanRequestAccess: "You can request access to, correction of, or deletion of your personal data at any time by contacting us below.",
  childrenSPrivacy: "Children’s Privacy",
  ourSiteIsnT: "Our site isn’t directed at children under 13, and we don’t knowingly collect data from them.",
  changesToThisPolicy: "Changes To This Policy",
  questionsAboutThisPolicy: "Questions about this policy? Reach out any time.",
  contactUs: "Contact Us",
  questionsAboutThisPolicy2: "Questions about this policy? Reach out any time.",
};
