/** Copy for the project detail page (/projects/details). */
export const projectDetail = {
  section1HeroOverlapping: "SECTION 1: HERO & OVERLAPPING MEDIA CARD",
  theVideoCardIs: "The video card is the hero's last flow child and hangs into the white",
  bodyBelowItBy: "body below it by --page-hero-hang.",
  anIntelligentElectronicHandpan: "An intelligent electronic handpan combining 9-zone capacitive",
  touchSensingGestureControl: "touch sensing, gesture control, and wireless MIDI built to give",
  a4000Year: "a 4,000-year-old instrument family a stage-ready, wireless",
  section2MainWhite: "SECTION 2: MAIN WHITE CONTENT BODY",
  whatShippedFromBench: "What Shipped, From Bench To Shell, and CTA Card",
  thePolypanIsAn: "The PolyPan is an electronic handpan designed to combine the rich harmonic acoustics of traditional handpans with the modern flexibility of a digital synthesizer and MIDI controller. Built from the ground up for stage performance and studio production, it features high-precision multi-zone touch sensing, motion-based expression, and zero-latency wireless connectivity.",
  weDevelopedAnIntegrated: "We developed an integrated hardware-firmware architecture that decouples physical touch acquisition from high-level MIDI synthesis, ensuring clean trigger detection and seamless gesture control.",
  comprehensiveBreakdownOfHardware: "Comprehensive breakdown of hardware components, processing specifications, wireless performance, and mechanical design.",
  fromTheMomentA: "From the moment a musician's fingertip strikes the surface to the transmission of MIDI data packets, the signal path is optimized for speed and accuracy.",
  touchLayer: "TOUCH LAYER",
  signalFiltering: "SIGNAL FILTERING",
  mcuFirmwareDsp: "MCU / FIRMWARE DSP",
  gestureSensing: "GESTURE SENSING",
  theEndToEnd: "The end-to-end development cycle from initial proof-of-concept to pilot production and mass manufacturing readiness.",
  architectureFeasibility: "Architecture & Feasibility",
  electronicsPcbV1: "Electronics & PCB v1",
  caseCadErgonomics: "Case CAD & Ergonomics",
  firmwareTouchTuning: "Firmware & Touch Tuning",
  bomOptimizationTesting: "BOM Optimization & Testing",
  pilotRunMassMfg: "Pilot Run & Mass Mfg",
  haveAHardwareIdea: "HAVE A HARDWARE IDEA WORTH PROTOTYPING?",
  tellUsWhatYou: "Tell us what you're building, whether it's on paper, in CAD, or half-coded, and we'll help you bring it to life.",
  section3FooterInteractive: "SECTION 3: FOOTER & INTERACTIVE CHAT WIDGET",
};
